### ISSUE TITLE
Landing page for User Dashboard

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#22]
User Stories:

- [ ]  The User can reach and see the landing page of the User Dashboard
- [ ]  The User can login on the landing page to the User Dashboard
- [ ] The User can choose the suitable template for his own User Dashboard
