### ISSUE TITLE
User feed

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#23]
As a scope of this Epic we need to:
- [ ] prepare the content for feeds (what kind of feeds with the categories distinction and what are the channels to collect feeds) in cooperation with WP10
- [ ] prepare the general configuration of the feed panel
- [ ] prepare the configuration for the concrete feed
- [ ] notification system
- [ ] user interface

**Comment by agpul** [comment]
no relevant any more
