### ISSUE TITLE
Widgets in the User Dashboard

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#24]
User Stories: 
- [ ] The User can choose from 2-3 templates of the User Dashboard 
- [x] The User can see the list of possible widgets in the User Dashboard
- [x] The User can add/remove widgets from his/her Dashboard
- [x]  The User can change the place and the size of each widget (edition, crud, resize, position, add items from the library)

Information about the widgets:
Possible widgets in the User Dashboard and how to reach each one:
1. Favorites - from OpenAire Explore, MP, SS (need to develop API)
2. Recommended services (from MP) - contact point MichałKo
3. Recommended training (from SS) - contact point MIchałKo
4. Recommended publications (from SS) - contact point Poznań (middleware MIchałKo)
5. Recommended data set -  contact point Poznań (middelware MIchałKo)
6. Recommended software -  contact point Poznań (middelware MIchałKo)
7. News from EOSC - API from Drupal - contact point Trust-IT (middelware Agnieszka) https://eosc-portal.eu/news-json-date/2022-01-01--2022-03-03 
8. Ordered Services (services added to the project from MP) with the possibility to order the services from UD
9. Projects (projects created in MP with the possibility to add projects from MP)
10. Recommendation for data sources
11. Top trending last week/month

Additional information about the widgets:
1. Favorites should be categorized
2. Add pictures where possible (for products)
3. ~~To make the view more interactive, boxes should move in some way~~
4. ~~User should be able to add like/dislike to the specific recommendation~~

**Comment by danielkryska** [comment]
Possible widgets in the User Dashboard and how to reach each one:
Favorites - from OpenAire Explore, MP, SS (need to develope API)
Recommended services (from MP) - contact point MichałKo
Recommended trainings (from SS) - contact point MIchałKo
Recommended publications (from SS) - contact point Poznań (middelware MIchałKo)
Recommended data set -  contact point Poznań (middelware MIchałKo)
Recommended software -  contact point Poznań (middelware MIchałKo)
News from EOSC - API from Drupal - contact point Trust-IT (middelware Agnieszka)
Ordered Services (services added to the project from MP) with possibility to order the services from UD
Projects (projects created in MP with possibility to add projects from MP)

Additional information about the widgets:
Favourities should be categorized
Add pictures where possible (for products)
Make the view more interactive, boxes shoudl move in some way

**Comment by danielkryska** [comment]
Pre-requisites:
- map user_id in recommender to aai_id
- allow more optional fields in the recommender request body
- get information about public URL to recommender

final schema
```
{
   "aai_id":"202090a4-de4c-4230-acba-6e2931d9e4444", // MP DB user id
   "unique_id":"5642c351-80fe-44cf-b606-304f2f338122", // user session unique id
   "timestamp":"2022-07-28T11:10:50.275Z",
   "visit_id":"202090a4-de4c-4230-acba-6e2931d9e37c", // every user action generate a new one
   "page_id":"some_page_identifier", // example: /services
   "panel_id":"v1", // should be default: v1
   "engine_version":"NCF", // should be default: NCF
}
```

Widgets:
2. Recommended services (from MP) - contact point MichałKo
3. Recommended training (from MP) - contact point MIchałKo
4. Recommended publications (from SS) - contact point Poznań (middleware MIchałKo)
5. Recommended data set -  contact point Poznań (middelware MIchałKo)
6. Recommended software -  contact point Poznań (middelware MIchałKo)
10. Recommendation for data sources

**Comment by danielkryska** [comment]
Pre-requisites:
- setup databus for user_actions

Widgets:
8. Ordered Services (services added to the project from MP) with the possibility to order the services from UD
9. Projects (projects created in MP with the possibility to add projects from MP)

**Comment by danielkryska** [comment]
Will we do it?
7. News from EOSC - API from Drupal - contact point Trust-IT (middelware Agnieszka) https://eosc-portal.eu/news-json-date/2022-01-01--2022-03-03

**Comment by danielkryska** [comment]
From where should we fetch the data?
11. Top trending last week/month

**Comment by agpul** [comment]
new endpoint for Drupal:
Could you please check now using this endpoint:
https://eosc-portal.eu/news-json-date/2022-01-01--2022-03-03
or this:
https://eosc-portal.eu/news-json-latest/10
