### ISSUE TITLE
Smoothing

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#25]
By @agpul 
Additional epic for issue without epic:)
- [ ] recreate common header
- [ ] recreate search in commons

By @danielkryska 
Improvements (or bug fixes)
**- [ ] update widget position on its change (backend)**
**- [ ] update widget size on its change (backend)**
- [ ] when lib is open, a dashboard should be shrunk by the lib width (UI)
- [ ] widgets should be added to the dashboard by drag and drop (UI)
      https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API
- [ ] add RWD to the landing page (UI)
- [ ] Improve landing page view (UI/UX)
- [ ] Improve widgets skeleton view (UI/UX)
