### ISSUE TITLE
First implementation of the User Dashboard

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#27]
General - 1 - 2.5d
- [x] setup local application (2h)
- [x] setup linters locally and externally (1d)
- [x] upgrade dependencies (1 day)

UX - 1 - 3.5d
- [x] draw wireframe of landing page (1d)
- [x] draw mock of landing page (1d)
- [ ] draw mock of templates page (4h)
- [x] draw wireframe of libs (4h)
- [x] draw mock of libs (4h)

UI - 12d
- [x] implement landing page (1d) (@jarek)
- [x] implement commons header (1h)
- [x] Implement error page (1h)
- [ ] implement commons search input (1h)
- [x] implement items grid (resize, move) (1d - 3d)
- [x] implement items grid crud (remove, edit) (1d - 3d)
- [x] implement widgets lib (select, add) (1d - 3d)
- [ ] implement templates page (3d - 5d)

Backend - 4d
- [x] fix authorization (4h)
- [x] provide UI_BASE_URL
- [x] add the domain to config
- [x] check auth
- [x] add write read system based on masks proposition (favorites, widgets) (3d - 5d)
- [ ] add recommendations endpoints: projects, services (4h)

Commons - 3d
- [ ] add new header to commons, based on new mock - 1d ( @goreck888 )
- [ ] add search bar with logo based on current solution in search service - (3d - 5d
