### ISSUE TITLE
Extend user API for onboarding team (WIP)

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/eosc-user-dashboard#39]
Privileges
- provider (read, write allowed user data)
- admin (the same as provider + add new providers + extends read/write access to user data)

- super admin (the same as admin + add new admins)

### New endpoints
- [ ] get users fields map, GET /user-data/fields, auth with `get_current_provider`
  - [ ] should return DB stored UserDataFields combined with GLOBAL_ACCESS_FIELDS

- [ ] create new data fields, POST /user-data/fields, auth with `get_current_admin`
  - [ ] fields names and labels must be unique
  - [ ] fields names and labels can't be the same as in GLOBAL_ACCESS_FIELDS
Body example
```json
[{
   "label": "User name",
  "field": "user.name",
"description": "It's user full name, contains surname and last name."
}, /**/]
```

- [ ] update data fields, POST /user-data/fields/{id}, auth with `get_current_admin`
  - [ ] fields names and labels must be unique
  - [ ] fields names and labels can't be the same as in GLOBAL_ACCESS_FIELDS
Body example
```json
{
   "label": "User name",
  "field": "user.name",
"description": "It's user full name, contains surname and last name."
}
```

- [ ] delete data fields, POST /user-data/fields/{id}, auth with `get_current_admin`
  - [ ] remove a field from all provider's read and write access
  - [ ] set crone to remove the field from user data 

- [ ] create a new provider, POST /provider/{user_aai_id}, auth with `get_current_admin`
  - [ ] set provider flag
- [ ] create a new admin, POST /admin/{user_aai_id}, auth with `get_current_superadmin`
  - [ ] set user provider flag 
  - [ ] set user admin flag
- [ ] extend read rights of provider, PUT /provider/{user_aai_id}/read-rights, auth with `get_current_admin`
  - [ ] right must exists
Body example
```json
["user.name", "user.email"]
```

- [ ] extend write rights of provider, PUT /provider/{user_aai_id}/write-rights, auth with `get_current_admin`
  -  [ ] extends also read rights
  - [ ] right must exists
Body example
```json
["user.name", "user.name"]
```

### DB and internal logic changes
- [ ] create new table UserDataFields
  - [ ] label and field must be unique 
  - [ ] field can contain only alphabet letters and '.' and '-' chars
        '.' mean nesting in object
        '-' is a words separator
```
id: int, primary_key
label: string, unique, not_unll
field: string, unique, not_null
description: string, not_null
```

Example

```
id: 1
label: "User name"
field: "user.name"
description: "It's user full name, contains surname and last name."
```

- [ ] `provider rights` table should change `read` field from string list to list of `UserDataFields` ids
- [ ] `provider rights` table should change `write` field from string list to list of `UserDataFields` ids

- [ ] GLOBAL_ACCESS_FIELDS should have a representation the same as UserDataFields without id

- [ ] providers user-data endpoints should work as previous
