### ISSUE TITLE
Create "recommended for you" widget

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/eosc-user-dashboard#67]
### Widget
![image](https://user-images.githubusercontent.com/31220811/199000436-4ff54626-4e5d-4478-8970-e12fbe4acaae.png)

### TODO
- [ ] Create Poznan recommendations endpoint for a specific type
- [ ] Create all recommendations endpoint
- [ ] Create config with all recommendations types
- [ ] Shuffle recommended items 
- [ ] Create a new recommendation component
- [ ] Create a new recommendations list
- [ ] Recommendations should be paginated (6 items per page)
- [ ] Add recommendations type filter (top bar of the widget)
- [ ] Add `Browse marketplace >` btn to the widget
- [ ] Add `Add to favorites` btn to the recommendation component

### Context
https://www.figma.com/file/RHmHoBRvx1oon6JwKK3Iaf/EOSC-Dashboard?node-id=19%3A2769

**Comment by danielkryska** [comment]
[how to export assets from figma](https://help.figma.com/hc/en-us/articles/360040028114-Guide-to-exports-in-Figma)

**Comment by danielkryska** [comment]
Our recommendations system: http://docker-fid.grid.cyf-kr.edu.pl:5000/

**Comment by danielkryska** [comment]
https://files.slack.com/files-pri/T7TV3MKD2-F04B3QPPCDD/zrzut_ekranu_2022-11-18_o_08.25.16.png

**Comment by danielkryska** [comment]
![image](https://user-images.githubusercontent.com/31220811/202645445-36290998-8af8-4ea8-8aa0-6d66801a53a8.png)
